version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - REACT_APP_SPOTIFY_CLIENT_ID=${REACT_APP_SPOTIFY_CLIENT_ID}
      - REACT_APP_SPOTIFY_CLIENT_SECRET=${REACT_APP_SPOTIFY_CLIENT_SECRET}
      - REACT_APP_OPENAI_API_KEY=${REACT_APP_OPENAI_API_KEY}
    volumes:
      - .:/app
